### ISSUE TITLE
how refreshing with git and task-editor is working ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/task-editor#15]
when we push to gihub new changes, sometimes they show up no task-editor, sometimes not. The refresh button doesn't seem to have any effect ? 
Is the refresh button pulling from github ?

**Comment by mblockelet** [comment]
The refresh button pulls from github indeed. When you filed this bugreport, the repository was in an inconsistent state and unable to pull and merge properly, as said in #14 . I'll see what I can do to solve that.
