### ISSUE TITLE
moving a task from outside task-editor - force sync ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/task-editor#16]
wy tried to move a task from a folder to another outside of task-editor, but then how do force sync task-editor to pull the chages from git ? It seems that the refresh button doesn't git pull ?

**Comment by remisharrock** [comment]
well, I think it is linked to https://github.com/France-ioi/task-editor/issues/15 and https://github.com/France-ioi/task-editor/issues/14 
sorry, duplicate here ?

**Comment by mblockelet** [comment]
Yes, closing this duplicate.
