### ISSUE TITLE
error during SVN checkout 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/task-editor#17]
When going to a task that was imported from GIT (for example http://task-editor.france-ioi.org/#edit/cspace/v2/C102/Week1/Hostel ) and clicking the task importer button, I get this error message :
Error during the SVN checkout: Error: unable to checkout (folder doesn't exist or invalid credentials).
Then when I click "open full interface" and "git" then back in the editor and in the task importer, it seems to work

**Comment by mblockelet** [comment]
I found why that happens, I'll fix it very soon.

**Comment by mblockelet** [comment]
Fixed.
