### ISSUE TITLE
spaces in file / folder names

### ISSUE THREAD

**Issue by petraBT** [France-ioi/task-editor#19]
We tried to clone an existing task into a folder with a space in its name and received the following error message:

fatal: pathspec 'testing' did not match any files

Are spaces not allowed in names and / or can they be allowed? How hard would this be to implement? Thanks!

**Comment by mblockelet** [comment]
I see why it happens, I'll try to fix it in a few hours.

In general, it's best to avoid spaces anyway, as it often causes issues in paths and URLs.

**Comment by mblockelet** [comment]
Fixed with 38e810c ; a test on your repository seems to indicate that it's working. Please tell me if you encounter other issues with spaces.
