### ISSUE TITLE
error reading JSON file

### ISSUE THREAD

**Issue by petraBT** [France-ioi/task-editor#20]
![Screen Shot 2019-12-02 at 10 42 04 AM](https://user-images.githubusercontent.com/33522257/69972972-9bfd5980-14f0-11ea-9a5c-b070fbdab043.png)

**Comment by mblockelet** [comment]
Hi,

You modified the JSON file `task_editor.json` by hand, and made an invalid JSON file. I fixed it for you in the repository.

(This is not a task-editor issue.)

**Comment by petraBT** [comment]
Thanks, Michel! Could you explain what I did to make the JSON file invalid? Is it impossible to use escaped quotation marks in the title?

On Dec 2, 2019, at 10:51 AM, mblockelet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

You modified the JSON file task_editor.json by hand, and made an invalid JSON file. I fixed it for you in the repository.

(This is not a task-editor issue.)

**Comment by mblockelet** [comment]
You can use escaped quotation marks without problem, but here, you had put too many quotations : `"title": "Modify output of \"Hello World\"""` with three quotes at the end, which was one too many quotes. I fixed it simply by changing to `"title": "Modify output of \"Hello World\""`, and now it is valid JSON!
