### ISSUE TITLE
New URL to import task into imt.algorea.com

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#22]
Hi Michel, 
I am trying to import task into the imt.algorea platform but I can do it because I can't fint the Algora URL. There is only the LTI URL and a static one. Would you help me? 
Best, 
Ella
https://task-editor.france-ioi.org/#edit/cspace%2F01%20C%20Programming%20Getting%20Started%2FUnit%201.0%20Welcome%20and%20the%20History%20of%20C%2F05%20Getting%20confortable%20with%20your%20keyboard%2F02_find%20special%20characters%20on%20the%20keyboard
![image](https://user-images.githubusercontent.com/19490273/73286494-ef8dda00-41f7-11ea-9075-fa8a03695037.png)

**Comment by mblockelet** [comment]
Hi, in this case, you can use directly the static URL in the platform. I updated the tutorial with the information.
