### ISSUE TITLE
Importing task from imt.algorea

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#25]
Hi Michel, 

I am trying to integrating tasks into the imt.algorea platform but I got this when integrating into edx studio. Thanks much for your help. 
Best, 

Ella 

https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@e6e75cef9df84cc69358e49b8e7381b0
This is for this task: 
https://imt.algorea.org/contents/5807-5801-745723603112028441-943610494122964335-1925718034702675433-548574824319546249-1620370338258757999/

![image](https://user-images.githubusercontent.com/19490273/73544959-95c92200-443a-11ea-8266-43959c6a5dba.png)

**Comment by EllaHa** [comment]
Same for chapter integration as LTI into edX

https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@e9317cf792024f9cbd2d3854d73a2335

![image](https://user-images.githubusercontent.com/19490273/73545795-5ac7ee00-443c-11ea-936c-d41b266e7b45.png)

**Comment by mblockelet** [comment]
Hello,

Sorry for the delay. This issue is now fixed.

Note that there is still the unrelated issue with LTI which requires you, after entering the URL, to refresh the page, as the first load will trigger an error. I updated the tutorial to point that out.

**Comment by EllaHa** [comment]
Thanks Michel for solving this issue. I will try again tomorrow. Do you think it will be able to solve this first load error?

**Comment by mblockelet** [comment]
I have no idea, that error has been there for a while and resides within the LTI protocol for the connection. I still have in my plans to look more into it.

At least it's only happening when the task is first integrated into the course, and hence won't ever appear to users.
