### ISSUE TITLE
No more access to any chapter on imt.algorea

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#26]
Hi Michel, 

The English interface doesn't seem to be working. 
I have been following the indication of adding but it doesn't work. 
?sLocale=en

Please see here : https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@e9317cf792024f9cbd2d3854d73a2335

![image](https://user-images.githubusercontent.com/19490273/73954191-c52bd300-4901-11ea-97e5-7e833d2ab08a.png)

**Comment by mblockelet** [comment]
Hi, it's now fixed. It was an odd issue with how edx.org is making LTI requests ; the bug was somehow not present on studio.edx.org . Not sure why, but the fix will now work in both cases.

**Comment by EllaHa** [comment]
thanks for solving that,
