### ISSUE TITLE
Error message that appears on edx that shouldn't (or I gess so) 

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#28]
![image](https://user-images.githubusercontent.com/19490273/74056073-8bca9480-49e1-11ea-8998-0b118a96a22d.png)

**Comment by mblockelet** [comment]
Hi, this message means that the connection to the server got interrupted. If it happens often it means there's an issue, but if it only happened once it might just mean a request failed for whichever reason at that time.
