### ISSUE TITLE
Remontée de notes ne fonctionne pas

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#29]
Bonjour Michel, 

Nous avons testé le bouton "validate", il semblerait que la remontée de notes vers edX ne fonctionne pas. 
Par exemple, Petra a fait le premier exercice mais aucune note ne remonte avec le bouton valider (pas d'apparition dans la progression algorea, ni dans la progression edX) (compte : Petra.B.Taylor@dartmouth.edu) 

Merci pour ton aide,

**Comment by mblockelet** [comment]
Bonjour,

Sur quel cours s'agit-il, et quel exercice / chapitre ? Cette information me permettra de voir plus précisément quel est le soucis.

Je viens de retester sur un exercice et un chapitre au hasard et ça fonctionne, du coup c'est qu'il doit y avoir un bug qui ne se produit que dans certains cas mais pas d'autres, il faudrait que je voie pourquoi.

**Comment by EllaHa** [comment]
Bonjour Michel, 
Sur aucun des cours cela ne fonctionne. 
Tu peux prendre par exemple l'activité 1 du cours pour mon compte (hamonic.ella@gmail.com). Impossible de faire remonter ma note. 

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/066b0480b13046e396208ef51d5c790b/09151bec3f5c43f2b56e181e2ad87d03/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40vertical%2Bblock%40fec93fa8856d4e2abae49ff713349779


![image](https://user-images.githubusercontent.com/19490273/75260535-09681000-57ea-11ea-8b7c-593d06ab5678.png)

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/dc24f5ecce354be1bbf01983250f9e74/e0f63e11d719409cb9d41864af2e3ba1/?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40sequential%2Bblock%40e0f63e11d719409cb9d41864af2e3ba1

![image](https://user-images.githubusercontent.com/19490273/75260616-2bfa2900-57ea-11ea-91dd-76c5e54c83e1.png)

**Comment by mblockelet** [comment]
Bonjour,

Comme indiqué dans le tutoriel, il faut utiliser les liens imt.algorea.org pour les exercices, afin que le score soit enregistré sur la plateforme, par exemple dans ce cas-là https://imt.algorea.org/contents/5807-5802-1052234341352848159-1430469227468202859-1435856789326096409-785827056651461930-1359568581258322411/, et non les anciens liens lti.algorea.org.

J'ai modifié par exemple l'activité que tu as indiquée ci-dessus, "Activity: find special characters on the keyboard", en mettant le bon lien. Une fois le bon lien utilisé, le score est bien enregistré (tu devrais pouvoir tester) :

![image](https://user-images.githubusercontent.com/11016337/75265647-1c2e1500-57e9-11ea-9cb4-5ddda458c8cc.png)

PS : Je vais corriger ce bug d'arrondi avec le score "16.670000076293945%".
