### ISSUE TITLE
hasUserTests in PEMTaskMetaData

### ISSUE THREAD

**Issue by simon-mauras** [France-ioi/task-editor#3]
I just found the following (closed) issue:
https://github.com/France-ioi/taskgrader/issues/12

But in the following file we have hasUserTests in FIOITaskMetaData
https://github.com/France-ioi/task-editor/blob/master/tasks/ioi/schema.json

**Comment by mblockelet** [comment]
Thank you, it was indeed in the wrong place in the editor schema. It's now fixed!
