### ISSUE TITLE
Integrating task into edX new process

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#32]
Hi Michel, 

I tried to follow your tutorial on how to integrate tasks into edX but now we just have problem statements appearing and this is not possible to submit any code... (the main menu is not appearing) I would appreciate your help to understand better how we can integrate tasks. 

https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@78f7c8007277491ba4267e555f3d0058

![image](https://user-images.githubusercontent.com/19490273/75270197-71beed80-57fa-11ea-9f6b-b3fb95eeec95.png)

All the best, 

Ella

**Comment by mblockelet** [comment]
Hello,

Thanks for the link, there was an issue in some cases in which the tabs would not display, hence I hadn't noticed it until now. This task was one such case, I fixed the issue now.

On a related note : is the current style for tabs fine?

![image](https://user-images.githubusercontent.com/11016337/75272591-1f7bcd80-57f6-11ea-8442-d9d28a322cbd.png)

or would you prefer to use the same style we had for tabs on previous versions of the MOOC?

![image](https://user-images.githubusercontent.com/11016337/75272641-315d7080-57f6-11ea-9c3b-4e2a24be5850.png)

**Comment by EllaHa** [comment]
Thanks Michel for your quick answer. This new design sounds great to me. I am confirming with the faculty.
