### ISSUE TITLE
Synchro git

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#35]
Bonjour Michel, 

J'ai découvert le bouton Synchronisation dépôt sur imt.algorea. Est-ce que cela veut dire que la synchro est manuelle ? Est-ce que c'est possible de l'automatiser (si oui, quels seraient les pour et contre ?)
Si nous faisons des synchros manuelles quelles sont les précautions à avoir si le cours est publié ?
Merci pour ces précisions, 

Belle journée, 

Ella

**Comment by mblockelet** [comment]
Bonjour,

Lorsque des sujets existants sont modifiés dans le task-editor, ils se retrouvent automatiquement mis à jour sur imt.algorea.org, pas de problème de ce côté. Je suppose que dans l'état actuel, il n'y aura pas besoin de faire de "synchronisation dépôt", car je crois que tous les sujets prévus existent déjà, même s'ils ne sont pas forcément terminés.

La "synchronisation dépôt" permet d'ajouter sur imt.algorea.org les nouveaux sujets qui seraient créés dans le dépôt ; du coup, il faut le faire à chaque fois qu'un nouveau sujet est créé puis intégré dans le cours. C'est aussi pour cela que c'est manuel : cela permet de voir ce qui a été rajouté, puis de corriger les problèmes si jamais un sujet a été créé alors qu'il ne devrait pas être présent dans le cours.

Ce serait compliqué de l'automatiser en raison de son fonctionnement, et je le déconseille pour la raison donnée ci-dessus.

Si le cours est publié, il faut simplement faire attention lors de la synchronisation aux messages de modification, en particulier si la synchronisation dit "nouvelle tâche ajoutée". En effet, si un sujet est ajouté, cela va affecter les moyennes de score (le nouveau sujet va être comptabilisé pour la moyenne), donc il ne faudrait pas qu'un sujet non voulu (par exemple une mauvaise manipulation par une des personnes écrivant des sujets) se retrouve comptabilisé.

Mais cela revient juste à s'assurer, tout d'abord, que les dossiers du dépôt sont propres, et ne contiennent que les sujets. A ce que je sache c'est déjà le cas, et il n'y a pas de raison pour que ça change. Du coup, pas besoin de synchronisation dépôt tant que tout va bien côté cspace !

Bonne journée,

Michel

**Comment by EllaHa** [comment]
Merci pour tous ces éléments Michel, c'est plus clair et ça me semble effectivement une bonne idée de ne pas automatiser ce process. 
Nous avons rajouté des tâches dans le MOOC 7, est-ce que c'est OK si je fais une synchro manuellement ?

**Comment by mblockelet** [comment]
Oui bien sûr, en cas de problème n'hésite pas à me tenir au courant.
