### ISSUE TITLE
index.html modified but once imported with LTI the changed are not reported to edx

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/task-editor#36]
here is the pb https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/606

**Comment by mblockelet** [comment]
Answered in the above issue!

**Comment by remisharrock** [comment]
still the same problem for quiz here ?
![image](https://user-images.githubusercontent.com/8048877/75664626-0c904f80-5c73-11ea-9b4a-b1fa2d28a21d.png)

**Comment by mblockelet** [comment]
Fixed too, I'm answering by mail!
