### ISSUE TITLE
The way we provide feedback to learners on quizzes: changing behaviour

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#37]
Hi Michel, 

The faculty members are suggesting for quizzes that in stead learners have to press a button to get feedbacks after they submitted a quiz, the feedback should show up automatically. 
Basically, can we get rid of the button show feedbacks and learners should have access to the feedbacks automatically after they submitted. 

Best, 
Ella

**Comment by mblockelet** [comment]
Hi, as said during the meeting, this had just been done today!
Cheers
