### ISSUE TITLE
Quizzes not showing up feedbacks

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#39]
It seems that the "show feedback" button is not appearing anymore on quizzes, is it a problem of settings? What is the default behaviour to show feedbacks to learners?

for example: https://imt.algorea.org/contents/5807-5802-1052234341352848159-1430469227468202859-1435856789326096409-785827056651461930-1359568581258322411/

**Comment by mblockelet** [comment]
Linked to #37 and #42, there is no button anymore as it's displayed right away... if there is no issue with the server. When there will be the new error message, it will be clear to the user what's happening.
