### ISSUE TITLE
impossible d'importer Telecom/demo1

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/task-editor#4]
J'essayer d'importer Telecom/demo1 mais voici l'erreur:
```
Status: Task file loading...

index.html: Loading task file...

Warning: possible error in _common paths.
```
puis:
```
Status: Task import finished (no resources to send).

index.html: Timeout while fetching resources from this file.

Warning: possible error in _common paths.
```

**Comment by mblockelet** [comment]
C'est dû à une limitation bête du task-editor, qui crée des index.html avec des chemins erronés si la tâche n'est pas dans un dossier de la forme
Telecom/folder1/folder2/taskFolder/

On va corriger ça rapidement :)

**Comment by remisharrock** [comment]
Ok je comprends. Faire attention du coup quand on copie une task déjà
existante de changer les chemins également avec ceux de la nouvelle 😁

Le mar. 24 avr. 2018 à 13:34, mblockelet <notifications@github.com> a
écrit :

**Comment by mblockelet** [comment]
Corrigé par 6ca8569 .
