### ISSUE TITLE
Changing title on imt.algorea, 

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#40]
If we change names of units and chapters on imt.algorea (the one that actually show up on the edX progress)
what happens when we will synchronize the git hub repository. Will all the titles will be the one that are on github? 
I guess so but I want to be sure. 
Does this mean that if we want to change titles of units, we should actually change them on github and not on the imt.algorea platform?  
Thanks for this information
Best, 

Ella

**Comment by mblockelet** [comment]
(was discussed during the meeting)
