### ISSUE TITLE
quiz grades not taken into account

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#42]
Sounds that grades are not taken into account on quizzes... but I guess we are going to talk about this on our online meeting.  I don't feedback nor grades. The only thing that appears is the "restart" button.  

![image](https://user-images.githubusercontent.com/19490273/75470415-ed52a300-5990-11ea-93b0-04cef3cc2bf9.png)

**Comment by EllaHa** [comment]
and the Progress tab is not showing up to me on this quiz on edX. https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020+type@vertical+block@39d3442be35f40e8bc07b9070cdb16ce

**Comment by mblockelet** [comment]
Hi, there was an issue with the quiz server. I'll modify the quiz system to add a message if there's an error, such as "There was an error getting your score, please try again in a few minutes.".

**Comment by mblockelet** [comment]
"the Progress tab is not showing up to me on this quiz on edX" did you mean the progress popup that appears at the bottom? If there was an issue with the grading, then the score didn't get back to the quiz, and no score was recorded, hence no progress popup.

**Comment by mblockelet** [comment]
Added the error message, it should appear soon on all quiz.
