### ISSUE TITLE
Urgent: problem with grading LTI

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#43]
Hi Michel, 

Thank you very much for all your work. 
I have been testing courses and it seems that we have a problem. 
It might be a problem on the edX platform and I will reach out to them to but I wanted to check with you. 
Basically, edx is not always taking into account our LTI exercices as practice exercises. 
Could you please make sure that your servers are grading information back to edX. For example, on MOOC 1, 
In "Writing your first program" we do have an exercise integrated into LTI it is listed as practice score and you can get 1 practice score, and I can get the point. 
We do have the same in the subsection that follows "Correcting simple syntax errors"  but, the LTI activity doesn't show on the edX progress page and there is no practice score (see screenshot below). 
Can you confirming that grades are sent to edX for this exercise? "Correcting simple syntax errors"
https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@b4ae761fa0204af4a262300e8a998f83 

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/progress

Thanks, 

Ella 

![image](https://user-images.githubusercontent.com/19490273/75565922-26514d00-5a4f-11ea-8f4f-f0c584db4961.png)

**Comment by mblockelet** [comment]
(answered by mail)

**Comment by EllaHa** [comment]
Please see here that we integrated LTI activities in each subsections (we use an external code activity platform in this course) :
- each unit of each subsection has one LTI component integrated. 
- all parameters are the same on the 2 LTI components 
- in both units learners should be able to get 1 point
- the progress page doesn't show the same information. 

In the subsection "[Writing your first program](https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@79e43fbbcbbd4fa196064db80ab0cfa8)" we do have an exercise integrated into LTI it is listed as practice score and you can get 1 practice score, and I can get the point.
We do have a LTI activity in the subsection that follows "[Correcting simple syntax errors](https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@b4ae761fa0204af4a262300e8a998f83)" but, the LTI activity doesn't show on the edX progress page and there is no practice score (see screenshot below).

It seems that the edX platform is not always showing up practice scores for LTI components. 
And this is not only affecting this course but the 7 courses of the Prof cert for several dozens of activities. 


Progress page

![image](https://user-images.githubusercontent.com/19490273/75681375-bda6e200-5c93-11ea-82a4-d503966596fe.png)



Unit which contains the activity listed in  Writing your first program

![image](https://user-images.githubusercontent.com/19490273/75681410-d0b9b200-5c93-11ea-8aab-3935c6b7d75b.png)


Unit which contains the activity listed in  Correcting simple sytax error
image.png
![image](https://user-images.githubusercontent.com/19490273/75681448-e3cc8200-5c93-11ea-9018-361de77ccd57.png)
