### ISSUE TITLE
Problem de synchronisation dépôt cspace // MOOC 7 unit 2 // sur imt.algorea

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#44]
Bonjour Michel, 

Pétra et ses teaching assistants ont modifié la structure de l'unité 2 du MOOC 7 dans cspace et taskeditor. J'ai effectué manuellement une synchronisation sur imt.algora, cependant les nouveaux exercices n'apparaissent pas dans imt.algorea. Une idée ? 
Merci pour ton aide: 
https://github.com/remisharrock/cspace/tree/master/07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries/Unit%207.2%20Modularization%20Libraries%20and%20Makefiles/02%20Creating%20and%20using%20a%20Makefile 

Bien à toi, 

Ella

**Comment by mblockelet** [comment]
Bonjour,

Aucune idée, quand j'ai testé ça a bien ajouté toutes les tâches dans l'unité 7.2, sans manipulation spéciale de mon côté. Est-ce que l'écran de synchronisation affichait une erreur particulière ? Est-ce qu'elle a affiché un message à propos des tâches non modifiées ?

**Comment by EllaHa** [comment]
Non ça n'a affiché aucun message. En revanche, maintenant je vois les nouvelles tâches donc c'est résolu, merci !

**Comment by EllaHa** [comment]
Hello Michel,

Ah non, je vois que l'on a à nouveau un problème de synchro. 


dans space il y a deux quiz https://github.com/remisharrock/cspace/tree/master/07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries/Unit%207.2%20Modularization%20Libraries%20and%20Makefiles/03%20Creating%20a%20static%20Library

![image](https://user-images.githubusercontent.com/19490273/75693269-fe5c2680-5ca6-11ea-8c9d-9e65e071a002.png)


mais rien n'apparait pour ce chapitre sur imt.algorea

https://imt.algorea.org/contents/5807-5802-1052234341352848159-125998167327598276-267504588561428429-12923383676082342/

![image](https://user-images.githubusercontent.com/19490273/75693373-2055a900-5ca7-11ea-9b5a-8d7ee6988d74.png)

merci pour ton aide

**Comment by mblockelet** [comment]
C'est bizarre, il me semblait pourtant avoir vu ces deux tâches rajoutées. Je viens de resynchroniser, et les deux tâches sont bien apparues ; je vais regarder ce qui a pu se passer.

**Comment by mblockelet** [comment]
Il y a un bug avec Git qui fait que la synchronisation détecte mal si les identifiants sont erronés (ou non-renseignés). Je n'avais pas remarqué vu que mes identifiants sont sauvegardés...

Si ça n'affiche aucun sujet, comme sur cette capture :
![image](https://user-images.githubusercontent.com/11016337/75695873-9acffa00-5ca2-11ea-9538-43c02860d6ed.png)
cela signifie qu'il n'a pas pu récupérer de sujets de Git.

Est-ce que pour la prochaine synchronisation, tu pourras cliquer sur le petit bouton "Display full interface", puis dans l'onglet Git, renseigner tes identifiants "Git username" et "Git password", cocher "Remember credentials" puis cliquer sur "Import files" ? A partir de là, ça devrait enregistrer tes identifiants et la synchronisation devrait se dérouler correctement les prochaines fois.

![image](https://user-images.githubusercontent.com/11016337/75696139-01551800-5ca3-11ea-9772-7ec64327ffe9.png)

Je vais corriger sous peu le bug qui fait que ça ne détecte pas l'erreur d'import Git, et du coup ne demande pas les identifiants si ceux-ci n'avaient pas déjà été enregistrés.

**Comment by EllaHa** [comment]
très bien, j'essaye ça ! merci.

**Comment by EllaHa** [comment]
Petra a supprimé 2 tasks sur space. 
03 
et 
05
https://github.com/remisharrock/cspace/tree/master/07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries/Unit%207.2%20Modularization%20Libraries%20and%20Makefiles/01%20Modularizing%20a%20program

![image](https://user-images.githubusercontent.com/19490273/75704532-d3c79900-5cb9-11ea-91cb-54624816fe09.png)


J'ai synchronisé en utilisant mes identifiants git. 

Les tasks apparaissent encore sur imt.algorea


![image](https://user-images.githubusercontent.com/19490273/75704404-99f69280-5cb9-11ea-9d0a-6815533c03e2.png)

Est-ce que tu conseilles de les supprimer manuellement ? 
D'ailleurs, quelle est la différence entre ces 2 moyens pour supprimer des tâches ? 

![image](https://user-images.githubusercontent.com/19490273/75704211-3c624600-5cb9-11ea-9549-338ee91624e3.png)

merci pour ces explications.

**Comment by mblockelet** [comment]
Bonsoir,

Oui, il faut les supprimer manuellement ; la synchronisation ne supprime pas les sujets pour ne pas perdre de sujets si jamais la suppression était une erreur.

Et il faut utiliser la deuxième option dont la traduction est plantée, "chapterEditor_destroy_item".

**Comment by EllaHa** [comment]
Ok merci.
