### ISSUE TITLE
les final projects apparaissent encore dans les progressions 

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#48]
Alors que je les ai théoriquement supprimés.

![image](https://user-images.githubusercontent.com/19490273/75777340-1b9bfe00-5d56-11ea-974e-f2885e5ad2f6.png)

![image](https://user-images.githubusercontent.com/19490273/75777366-2787c000-5d56-11ea-951f-afbd7b45fd14.png)

**Comment by mblockelet** [comment]
Quand j'ai regardé, le Final Project de 7.4 n'apparaissait plus. Parfois il faut attendre un peu la synchronisation.

J'en ai profité pour supprimer les autres Final Projects comme ça c'est fait.
