### ISSUE TITLE
c code HTML formatting

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/task-editor#5]
When writing directives, would it be possible to have a C code automatic formatting plugin or automatic formatter ? 
Like http://hilite.me/ 
?
Thanks !

**Comment by chrissmiller** [comment]
If the editor is tinyMCE, the plugin CodeSample will automatically translate to proper C syntax (must be enabled when the editor is loaded and be in the correct directory).

**Comment by mblockelet** [comment]
Hi, I installed CodeSample onto the editor, and the relevant dependencies onto the task platform. There's now a new button in the tinyMCE editor, `{,}` which will allow you to include code samples.
